version: '3'

services:
  file-storage:
    image: minio/minio:latest
    restart: unless-stopped
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: 'minio-root'
      MINIO_ROOT_PASSWORD: 'minio-root'

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
    ports:
      - '5552:5552'
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:alpine
    restart: on-failure
    environment:
      REDIS_USER: 'redis'
      REDIS_PASSWORD: 'redis'
      REDIS_USER_PASSWORD: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - './redis-data:/data'
