// Code generated by "stringer -type=TaskStatus"; DO NOT EDIT.

package dto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Failed - -1]
	_ = x[Received-0]
	_ = x[Pending-1]
	_ = x[Processing-2]
	_ = x[Successful-3]
}

const _TaskStatus_name = "FailedReceivedPendingProcessingSuccessful"

var _TaskStatus_index = [...]uint8{0, 6, 14, 21, 31, 41}

func (i TaskStatus) String() string {
	i -= -1
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
