[server.http]
address = "0.0.0.0:2893"

[server.http.logger]
level = "info"
enable_loki = true
address = "loki:3100"

[ocr.dedoc]
address = "http://dedoc:8004"
timeout = 300

[docstorage.docsearcher]
address = "http://doc-searcher:2892"

[cacher.redis]
address = "redis:6379"
username = "redis"
password = "redis"
expired = 3600

[queue.rmq]
address = "amqp://localhost:5672"
exchange = "watchtower"
routing_key = "task"
queue = "watchtower-tasks"

[cloud.s3]
address = "cloud-storage:9000"
access_id = "minio-root"
secret_key = "minio-root"
enable_ssl = false
token = ""
watched_dirs = [
    "common-folder"
]
