[server.http]
address="0.0.0.0:2893"

[server.http.logger]
level="info"
enable_loki=false
address="loki:3100"

[ocr.dedoc]
address="dedoc:8004"
enable_ssl=false
timeout=300

[storage.docsearcher]
address="doc-searcher:2892"
enable_ssl=false

[cacher.redis]
address="redis:6379"
username="redis"
password="redis"
expired=3600

[queue.rmq]
address="amqp://rabbitmq:5672"
exchange="watchtowerr"
routing_key="task"
queue_name="watchtower-tasks"

[cloud.minio]
address="cloud-storage:9000"
access_id="minio-root"
secret_key="minio-root"
enable_ssl=false
token=""

[tokenizer.vectorizer]
address="vectorizer:8001"
enable_ssl=false
chunk_size=800
chunk_overlap=100
return_chunks=false
chunks_by_self=false
