[settings]
chunk_size = 50000
chunk_overlap = 1000

[server.http]
address = "0.0.0.0:2893"

[server.http.logger]
level = "info"
address = "loki:3100"
enable_loki = true

[server.http.tracer]
address = "jaeger:4317"
enable_jaeger = false

[ocr.dedoc]
address = "http://localhost:8004"
timeout = 300

[docstorage.docsearcher]
address = "http://localhost:2892"

[cacher.redis]
address = "localhost:6379"
username = "redis"
password = "redis"
expired = 3600

[queue.rmq]
address = "amqp://localhost:5672"
exchange = "watchtower"
routing_key = "task"
queue = "watchtower-tasks"

[cloud.s3]
address = "localhost:9000"
access_id = "minio-root"
secret_key = "minio-root"
enable_ssl = false
token = ""
