[orchestrator]
semaphore_size = 10

[otlp.logger]
level = "info"
address = "http://localhost:3100"
enable_loki = false

[otlp.tracer]
address = "localhost:4317"
enable_jaeger = false

[server.http]
address = "0.0.0.0:2893"

[storage.s3]
address = "localhost:9000"
access_id = "minio-root"
secret_key = "minio-root"
enable_ssl = false
token = ""

[task.storage.redis]
address = "localhost:6379"
username = "redis"
password = "redis"
expired = 360

[task.queue.rmq]
address = "amqp://localhost:5672"
exchange = "test-watchtower"
routing_key = "test-task"
queue = "test-watchtower-tasks"

[task.processor.docparser]
address = "http://localhost:8012"
timeout = 300

[task.processor.docstorage]
address = "http://localhost:2892"
timeout = 300
