[orchestrator]
semaphore_size = 10

[otlp.logger]
level = "info"
address = "http://loki:3100"
enable_loki = false

[otlp.tracer]
address = "jaeger:4317"
enable_jaeger = false

[server.http]
address = "0.0.0.0:2893"

[storage.s3]
address = "minio:9000"
access_id = "minio-root"
secret_key = "minio-root"
enable_ssl = false
token = ""

[task.storage.redis]
address = "redis:6379"
username = "redis"
password = "redis"
expired = 3600

[task.queue.rmq]
address = "amqp://rabbitmq:5672"
exchange = "watchtower"
routing_key = "task"
queue = "watchtower-tasks"

[task.processor.docparser]
address = "http://doc-parser:8012"
timeout = 300

[task.processor.docstorage]
address = "http://doc-searcher:2892"
timeout = 300
