[settings]
pipeline_semaphore_size = 10

[server.http]
address = "0.0.0.0:2893"

[server.logger]
level = "debug"
enable_loki = false
address = "localhost:3100"

[server.tracer]
address = "localhost:4317"
enable_jaeger = false

[recognizer.dedoc]
address = "http://localhost:8004/api/v1"
timeout = 300

[storage.document.docsearcher]
address = "http://localhost:2892/api/v1"
timeout = 300

[task.storage.redis]
address = "localhost:6379"
username = "redis"
password = "redis"
expired = 360

[task.queue.rmq]
address = "amqp://localhost:5672"
exchange = "test-watchtower"
routing_key = "test-task"
queue = "test-watchtower-tasks"

[storage.object.s3]
address = "localhost:9000"
access_id = "minio-root"
secret_key = "minio-root"
enable_ssl = false
token = ""
