[server.http]
address="0.0.0.0:2893"

[server.http.logger]
level="info"
enable_loki=false
address="localhost:3100"

[ocr.dedoc]
address="localhost:8004"
enable_ssl=false
timeout=300

[storage.docsearcher]
address="localhost:2892"
enable_ssl=false

[cacher.redis]
address="localhost:6379"
username="redis"
password="redis"
expired=360

[queue.rmq]
address="amqp://localhost:5672"
exchange="watchtower"
routing_key="task"
queue_name="watchtower-tasks"

[cloud.minio]
address="localhost:9000"
access_id="minio-root"
secret_key="minio-root"
enable_ssl=false
token=""
watched_dirs=[
    "test-bucket"
]

[tokenizer.vectorizer]
address="localhost:8001"
enable_ssl=false
chunk_size=800
chunk_overlap=100
return_chunks=false
chunks_by_self=false
