// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tasks/all": {
            "post": {
                "description": "Get all processing documents",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get all processing documents",
                "operationId": "get-processing-documents",
                "parameters": [
                    {
                        "description": "File names to fetch processing status",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.FetchAllDocuments"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request message",
                        "schema": {
                            "$ref": "#/definitions/httpserver.BadRequestForm"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ServerErrorForm"
                        }
                    }
                }
            }
        },
        "/tasks/fetch": {
            "post": {
                "description": "Load processing/unrecognized/done documents by names list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Fetch processing documents",
                "operationId": "fetch-documents",
                "parameters": [
                    {
                        "description": "File names to fetch processing status",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.FetchDocumentsList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TaskEvent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request message",
                        "schema": {
                            "$ref": "#/definitions/httpserver.BadRequestForm"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ServerErrorForm"
                        }
                    }
                }
            }
        },
        "/watcher/attach": {
            "post": {
                "description": "Attach new directory to watcher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watcher"
                ],
                "summary": "Attach new directory to watcher",
                "operationId": "folders-attach",
                "parameters": [
                    {
                        "description": "File entity",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.AttachDirectoryForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request message",
                        "schema": {
                            "$ref": "#/definitions/httpserver.BadRequestForm"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ServerErrorForm"
                        }
                    }
                }
            }
        },
        "/watcher/{bucket}": {
            "delete": {
                "description": "Attach new directory to watcher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watcher"
                ],
                "summary": "Attach new directory to watcher",
                "operationId": "folders-detach",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ids",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request message",
                        "schema": {
                            "$ref": "#/definitions/httpserver.BadRequestForm"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/httpserver.ServerErrorForm"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.TaskEvent": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/dto.TaskStatus"
                },
                "status_text": {
                    "type": "string"
                }
            }
        },
        "dto.TaskStatus": {
            "type": "integer",
            "enum": [
                -1,
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Failed",
                "Received",
                "Pending",
                "Processing",
                "Successful"
            ]
        },
        "httpserver.AttachDirectoryForm": {
            "type": "object",
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "example": "test-folder"
                },
                "directory": {
                    "type": "string",
                    "example": "/directory"
                }
            }
        },
        "httpserver.BadRequestForm": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad Request message"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "httpserver.FetchAllDocuments": {
            "type": "object",
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "example": "test-folder"
                }
            }
        },
        "httpserver.FetchDocumentsList": {
            "type": "object",
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "example": "test-folder"
                },
                "status": {
                    "type": "string",
                    "example": "Pending"
                }
            }
        },
        "httpserver.ResponseForm": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Done"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "httpserver.ServerErrorForm": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Server Error message"
                },
                "status": {
                    "type": "integer",
                    "example": 503
                }
            }
        }
    },
    "tags": [
        {
            "description": "APIs to manage cloud watchers",
            "name": "watcher"
        },
        {
            "description": "APIs to get status tasks",
            "name": "tasks"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Watchtower service",
	Description:      "Watchtower is a project designed to provide processing files created into cloud by events.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
