// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cloud/bucket": {
            "put": {
                "description": "Create new bucket into cloud",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buckets"
                ],
                "summary": "Create new bucket into cloud",
                "operationId": "create-bucket",
                "parameters": [
                    {
                        "description": "Bucket name to create",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.CreateBucketForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/buckets": {
            "get": {
                "description": "Get watched bucket list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buckets"
                ],
                "summary": "Get watched bucket list",
                "operationId": "get-buckets",
                "responses": {
                    "200": {
                        "description": "Loaded buckets info",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/form.BucketSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}": {
            "delete": {
                "description": "Remove bucket from cloud",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buckets"
                ],
                "summary": "Remove bucket from cloud",
                "operationId": "remove-bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to remove",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file": {
            "delete": {
                "description": "Remove file from cloud",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Remove file from cloud",
                "operationId": "remove-file-2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to remove file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parameters to remove file",
                        "name": "file_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/attributes": {
            "post": {
                "description": "Get file attributes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get file attributes",
                "operationId": "get-file-attrs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to get list files",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parameters to get list files",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.GetFileAttributesForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket or Object not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/copy": {
            "post": {
                "description": "Copy file to another location into bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Copy file to another location into bucket",
                "operationId": "copy-file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name of src file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Params to copy file",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.CopyFileForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket or file not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/download": {
            "post": {
                "description": "Download file from cloud",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Download file from cloud",
                "operationId": "download-file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to download file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parameters to download file",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.DownloadFileForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returned file bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/move": {
            "post": {
                "description": "Move file to another location into bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Move file to another location into bucket",
                "operationId": "move-file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name of src file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Params to move file",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.CopyFileForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket or file not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/remove": {
            "delete": {
                "description": "Remove file from cloud",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Remove file from cloud",
                "operationId": "remove-file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to remove file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parameters to remove file",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.RemoveFileForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/share": {
            "post": {
                "description": "Get share URL for file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "Get share URL for file",
                "operationId": "share-file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to share file",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parameters to share file",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.ShareFileForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "URL with shared file",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket of object not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/file/upload": {
            "put": {
                "description": "Upload files to cloud",
                "consumes": [
                    "multipart/form"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload files to cloud",
                "operationId": "upload-files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to upload files",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Files multipart form",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File datetime expired like 2025-01-01T12:01:01Z",
                        "name": "expired",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/files": {
            "post": {
                "description": "Get files list into bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get files list into bucket",
                "operationId": "get-list-files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to get list files",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parameters to get list files",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.GetFilesForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/cloud/{bucket}/folder": {
            "post": {
                "description": "Create empty folder into cloud storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Create empty folder into cloud storage",
                "operationId": "create-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to create folder",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Params to create folder",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.FolderForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete empty folder into cloud storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Delete folder into cloud storage",
                "operationId": "delete-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket name to delete folder",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Params to delete folder",
                        "name": "jsonQuery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.FolderForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/form.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{bucket}": {
            "get": {
                "description": "Load tasks (processing/unrecognized/done) of uploaded files",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Load processing tasks of uploaded files into bucket",
                "operationId": "load-tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket id of uploaded files",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Status tasks to filter target result",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loaded tasks",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/form.TaskSchema"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Bucket not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{bucket}/{task_id}": {
            "get": {
                "description": "Load processing/unrecognized/done task by id of uploaded file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Load processing task by id",
                "operationId": "load-task-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket id of processing task",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Loaded tasks",
                        "schema": {
                            "$ref": "#/definitions/form.TaskSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request error",
                        "schema": {
                            "$ref": "#/definitions/form.BadRequestError"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/form.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/form.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Server does not available",
                        "schema": {
                            "$ref": "#/definitions/form.ServerUnavailableError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "form.BadRequestError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad Request message"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "form.BucketSchema": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "form.CopyFileForm": {
            "type": "object",
            "properties": {
                "dst_path": {
                    "type": "string",
                    "example": "test-document.docx"
                },
                "src_path": {
                    "type": "string",
                    "example": "old-test-document.docx"
                }
            }
        },
        "form.CreateBucketForm": {
            "type": "object",
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "example": "test-bucket"
                }
            }
        },
        "form.DownloadFileForm": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string",
                    "example": "test-file.docx"
                }
            }
        },
        "form.FolderForm": {
            "type": "object",
            "properties": {
                "prefix": {
                    "type": "string",
                    "example": "test-folder"
                }
            }
        },
        "form.GetFileAttributesForm": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "example": "test-file.docx"
                }
            }
        },
        "form.GetFilesForm": {
            "type": "object",
            "properties": {
                "directory": {
                    "type": "string",
                    "example": "test-folder/"
                }
            }
        },
        "form.InternalServerError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Internal server error message"
                },
                "status": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "form.NotFoundError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "form.RemoveFileForm": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string",
                    "example": "test-file.docx"
                }
            }
        },
        "form.ServerUnavailableError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Server unavailable error message"
                },
                "status": {
                    "type": "integer",
                    "example": 503
                }
            }
        },
        "form.ShareFileForm": {
            "type": "object",
            "properties": {
                "expired_secs": {
                    "type": "integer",
                    "example": 3600
                },
                "file_path": {
                    "type": "string",
                    "example": "test-file.docx"
                }
            }
        },
        "form.Success": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Done"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "form.TaskSchema": {
            "type": "object",
            "properties": {
                "bucket_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modified_at": {
                    "type": "string"
                },
                "object_data_size": {
                    "type": "integer"
                },
                "object_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "status_text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
