definitions:
  dto.TaskEvent:
    properties:
      bucket:
        type: string
      created_at:
        type: string
      file_path:
        type: string
      file_size:
        type: integer
      id:
        type: string
      modified_at:
        type: string
      status:
        $ref: '#/definitions/dto.TaskStatus'
      status_text:
        type: string
    type: object
  dto.TaskStatus:
    enum:
    - -1
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Failed
    - Received
    - Pending
    - Processing
    - Successful
  httpserver.AttachDirectoryForm:
    properties:
      bucket_name:
        example: test-folder
        type: string
      directory:
        example: /directory
        type: string
    type: object
  httpserver.BadRequestForm:
    properties:
      message:
        example: Bad Request message
        type: string
      status:
        example: 400
        type: integer
    type: object
  httpserver.FetchAllDocuments:
    properties:
      bucket_name:
        example: test-folder
        type: string
    type: object
  httpserver.FetchDocumentsList:
    properties:
      bucket_name:
        example: test-folder
        type: string
      status:
        example: Pending
        type: string
    type: object
  httpserver.ResponseForm:
    properties:
      message:
        example: Done
        type: string
      status:
        example: 200
        type: integer
    type: object
  httpserver.ServerErrorForm:
    properties:
      message:
        example: Server Error message
        type: string
      status:
        example: 503
        type: integer
    type: object
info:
  contact: {}
  description: Watchtower is a project designed to provide processing files created
    into cloud by events.
  title: Watchtower service
  version: 0.0.1
paths:
  /tasks/all:
    post:
      consumes:
      - application/json
      description: Get all processing documents
      operationId: get-processing-documents
      parameters:
      - description: File names to fetch processing status
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserver.FetchAllDocuments'
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserver.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserver.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserver.ServerErrorForm'
      summary: Get all processing documents
      tags:
      - tasks
  /tasks/fetch:
    post:
      consumes:
      - application/json
      description: Load processing/unrecognized/done documents by names list
      operationId: fetch-documents
      parameters:
      - description: File names to fetch processing status
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserver.FetchDocumentsList'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            items:
              $ref: '#/definitions/dto.TaskEvent'
            type: array
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserver.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserver.ServerErrorForm'
      summary: Fetch processing documents
      tags:
      - tasks
  /watcher/{bucket}:
    delete:
      consumes:
      - application/json
      description: Attach new directory to watcher
      operationId: folders-detach
      parameters:
      - description: Folder ids
        in: path
        name: bucket
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserver.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserver.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserver.ServerErrorForm'
      summary: Attach new directory to watcher
      tags:
      - watcher
  /watcher/attach:
    post:
      consumes:
      - application/json
      description: Attach new directory to watcher
      operationId: folders-attach
      parameters:
      - description: File entity
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserver.AttachDirectoryForm'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserver.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserver.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserver.ServerErrorForm'
      summary: Attach new directory to watcher
      tags:
      - watcher
swagger: "2.0"
tags:
- description: APIs to manage cloud watchers
  name: watcher
- description: APIs to get status tasks
  name: tasks
