kind: pipeline
type: docker
name: watchtower-ci

environment:
  GO_VERSION: 1.24

steps:
  - name: cache-built-go
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /usr/local/go
        - /drone/src
    volumes:
      - name: go-targets
        path: /cache

  - name: build
    image: golang:1.24
    depends_on:
      - cache-built-go
    commands:
      - go build watchtower/cmd/watchtower
    volumes:
      - name: go-targets
        path: /cache
 
  - name: lint
    image: golang:1.24
    depends_on:
      - build
    commands:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - golangci-lint run ./...
    volumes:
      - name: go-targets
        path: /cache

  - name: test
    image: golang:1.24
    depends_on:
      - lint
      - build 
    commands:
      - go test watchtower/tests
    volumes:
      - name: go-targets
        path: /cache

  - name: notify-gitea
    image: plugins/gitea-release
    settings:
      base_url: ${GITEA_SERVER}
      api_key:
        from_secret: gitea_token
      files: 
        - config
        #- docs
        - "*.md"
        - "bin/*"
    when:
      event: tag

volumes:
  - name: go-targets
    temp: {}
